version: "3.9"

services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./backend-drf/.env.production
    volumes:
      - postgres_data:version: "3.9"

services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./backend-drf/.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend-drf
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn clickmart_main.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - ./backend-drf/.env.production
    expose:
      - "8000"
    volumes:
      - ./backend-drf/staticfiles:/static
      - ./backend-drf/media:/media
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend-drf/staticfiles:/static
      - ./backend-drf/media:/media
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:

